name: Gather tweet data
on:
  schedule:
    # run this job every 10 minutes
    - cron:  '*/10 * * * *'

jobs:
  build:
    name: Regurgitate Tweets
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci --production
      
      - name: Scrape Data
        run: node scrape.js

      - name: Generate Markov Chains
        run: node generate.js

      - name: Tweet from Chains
        run: node tweet.js
