name: Gather tweet data
on:
  schedule:
    # run this job every 1 hour
    - cron:  '0 */1 * * *'

jobs:
  build:
    name: Generate Tweets
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci --production
      
      - name: Scrape Data
        run: node scrape.js

      - name: Generate Chains and tweet from each
        run: node tweet.js
